### ISSUE TITLE
The model gpt-4 does not exist

### ISSUE THREAD

**Issue by matt-bailey** [ryonakae/figma-plugin-figma-gpt#12]
I'm having a similar issue to others I think. I've entered my API key, but I just get an error message saying "the model gpt-4 does not exist or you do not have access to it". I'm also getting another error message saying I've exceeded my quota, but that can't be correct because I've only just signed up for ChatGPT-4.

For now I'll continue to use the ChatGPT web interface, but it would be great if this plugin could be fixed as having direct access in Figma would be amazing.

![Screenshot 2024-03-14 at 13 17 54](https://github.com/ryonakae/figma-plugin-figma-gpt/assets/969385/057cde57-31e5-4db3-9229-eb45cefc6b84)

![Screenshot 2024-03-14 at 13 18 18](https://github.com/ryonakae/figma-plugin-figma-gpt/assets/969385/85a51ef9-49f5-40ba-bcc3-1c57ef03dd5b)

**Comment by ryonakae** [comment]
@matt-bailey Sorry for the delay in response. We have released an update today to support the latest GPT models.
